package Enums;

public enum CountryCurrencyCodes {

    AFN("Afghani", "AFGHANISTAN"),
    ALL("Lek", "ALBANIA"),
    DZD("Algerian Dinar", "ALGERIA"),
    AOA("Kwanza", "ANGOLA"),
    XCD("East Caribbean Dollar", "ANGUILLA"),
    ARS("Argentine Peso", "ARGENTINA"),
    AMD("Armenian Dram", "ARMENIA"),
    AWG("Aruban Florin", "ARUBA"),
    AUD("Australian Dollar", "AUSTRALIA"),
    AZN("Azerbaijanian Manat", "AZERBAIJAN"),
    BSD("Bahamian Dollar", "BAHAMAS (THE)"),
    BHD("Bahraini Dinar", "BAHRAIN"),
    BDT("Taka", "BANGLADESH"),
    BBD("Barbados Dollar", "BARBADOS"),
    BYR("Belarussian Ruble", "BELARUS"),
    BZD("Belize Dollar", "BELIZE"),
    XOF("CFA Franc BCEAO", "BENIN"),
    BMD("Bermudian Dollar", "BERMUDA"),
    BTN("Ngultrum", "BHUTAN"),
    BOB("Boliviano", "BOLIVIA (PLURINATIONAL STATE OF)"),
    BOV("Mvdol", "BOLIVIA (PLURINATIONAL STATE OF)"),
    BAM("Convertible Mark", "BOSNIA AND HERZEGOVINA"),
    BWP("Pula", "BOTSWANA"),
    BRL("Brazilian Real", "BRAZIL"),
    BND("Brunei Dollar", "BRUNEI DARUSSALAM"),
    BGN("Bulgarian Lev", "BULGARIA"),
    BIF("Burundi Franc", "BURUNDI"),
    CVE("Cabo Verde Escudo", "CABO VERDE"),
    KHR("Riel", "CAMBODIA"),
    XAF("CFA Franc BEAC", "CAMEROON"),
    CAD("Canadian Dollar", "CANADA"),
    KYD("Cayman Islands Dollar", "CAYMAN ISLANDS (THE)"),
    CLF("Unidad de Fomento", "CHILE"),
    CLP("Chilean Peso", "CHILE"),
    CNY("Yuan Renminbi", "CHINA"),
    COP("Colombian Peso", "COLOMBIA"),
    COU("Unidad de Valor Real", "COLOMBIA"),
    KMF("Comoro Franc", "COMOROS (THE)"),
    CDF("Congolese Franc", "CONGO (THE DEMOCRATIC REPUBLIC OF THE)"),
    CRC("Costa Rican Colon", "COSTA RICA"),
    HRK("Kuna", "CROATIA"),
    CUC("Peso Convertible", "CUBA"),
    CUP("Cuban Peso", "CUBA"),
    ANG("Netherlands Antillean Guilder", "CURAÇAO"),
    CZK("Czech Koruna", "CZECH REPUBLIC (THE)"),
    DKK("Danish Krone", "DENMARK"),
    DJF("Djibouti Franc", "DJIBOUTI"),
    DOP("Dominican Peso", "DOMINICAN REPUBLIC (THE)"),
    EGP("Egyptian Pound", "EGYPT"),
    SVC("El Salvador Colon", "EL SALVADOR"),
    ERN("Nakfa", "ERITREA"),
    ETB("Ethiopian Birr", "ETHIOPIA"),
    EUR("Euro", "EUROPEAN UNION"),
    FKP("Falkland Islands Pound", "FALKLAND ISLANDS (THE) [MALVINAS]"),
    FJD("Fiji Dollar", "FIJI"),
    XPF("CFP Franc", "FRENCH POLYNESIA"),
    GMD("Dalasi", "GAMBIA (THE)"),
    GEL("Lari", "GEORGIA"),
    GHS("Ghana Cedi", "GHANA"),
    GIP("Gibraltar Pound", "GIBRALTAR"),
    GTQ("Quetzal", "GUATEMALA"),
    GNF("Guinea Franc", "GUINEA"),
    GYD("Guyana Dollar", "GUYANA"),
    HTG("Gourde", "HAITI"),
    HNL("Lempira", "HONDURAS"),
    HKD("Hong Kong Dollar", "HONG KONG"),
    HUF("Forint", "HUNGARY"),
    ISK("Iceland Krona", "ICELAND"),
    INR("Indian Rupee", "INDIA"),
    IDR("Rupiah", "INDONESIA"),
    XDR("SDR (Special Drawing Right)", "INTERNATIONAL MONETARY FUND (IMF) "),
    IRR("Iranian Rial", "IRAN (ISLAMIC REPUBLIC OF)"),
    IQD("Iraqi Dinar", "IRAQ"),
    ILS("New Israeli Sheqel", "ISRAEL"),
    JMD("Jamaican Dollar", "JAMAICA"),
    JPY("Yen", "JAPAN"),
    JOD("Jordanian Dinar", "JORDAN"),
    KZT("Tenge", "KAZAKHSTAN"),
    KES("Kenyan Shilling", "KENYA"),
    KPW("North Korean Won", "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF)"),
    KRW("Won", "KOREA (THE REPUBLIC OF)"),
    KWD("Kuwaiti Dinar", "KUWAIT"),
    KGS("Som", "KYRGYZSTAN"),
    LAK("Kip", "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE)"),
    LBP("Lebanese Pound", "LEBANON"),
    LSL("Loti", "LESOTHO"),
    ZAR("Rand", "LESOTHO"),
    LRD("Liberian Dollar", "LIBERIA"),
    LYD("Libyan Dinar", "LIBYA"),
    MOP("Pataca", "MACAO"),
    MKD("Denar", "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)"),
    MGA("Malagasy Ariary", "MADAGASCAR"),
    MWK("Kwacha", "MALAWI"),
    MYR("Malaysian Ringgit", "MALAYSIA"),
    MVR("Rufiyaa", "MALDIVES"),
    MRO("Ouguiya", "MAURITANIA"),
    MUR("Mauritius Rupee", "MAURITIUS"),
    XUA("ADB Unit of Account", "MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP"),
    MXN("Mexican Peso", "MEXICO"),
    MXV("Mexican Unidad de Inversion (UDI)", "MEXICO"),
    MDL("Moldovan Leu", "MOLDOVA (THE REPUBLIC OF)"),
    MNT("Tugrik", "MONGOLIA"),
    MAD("Moroccan Dirham", "MOROCCO"),
    MZN("Mozambique Metical", "MOZAMBIQUE"),
    MMK("Kyat", "MYANMAR"),
    NAD("Namibia Dollar", "NAMIBIA"),
    NPR("Nepalese Rupee", "NEPAL"),
    NZD("New Zealand Dollar", "NEW ZEALAND"),
    NIO("Cordoba Oro", "NICARAGUA"),
    NGN("Naira", "NIGERIA"),
    NOK("Norwegian Krone", "NORWAY"),
    OMR("Rial Omani", "OMAN"),
    PKR("Pakistan Rupee", "PAKISTAN"),
    PAB("Balboa", "PANAMA"),
    PGK("Kina", "PAPUA NEW GUINEA"),
    PYG("Guarani", "PARAGUAY"),
    PEN("Nuevo Sol", "PERU"),
    PHP("Philippine Peso", "PHILIPPINES (THE)"),
    PLN("Zloty", "POLAND"),
    QAR("Qatari Rial", "QATAR"),
    RON("Romanian Leu", "ROMANIA"),
    RUB("Russian Ruble", "RUSSIAN FEDERATION (THE)"),
    RWF("Rwanda Franc", "RWANDA"),
    SHP("Saint Helena Pound", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA"),
    WST("Tala", "SAMOA"),
    STD("Dobra", "SAO TOME AND PRINCIPE"),
    SAR("Saudi Riyal", "SAUDI ARABIA"),
    RSD("Serbian Dinar", "SERBIA"),
    SCR("Seychelles Rupee", "SEYCHELLES"),
    SLL("Leone", "SIERRA LEONE"),
    SGD("Singapore Dollar", "SINGAPORE"),
    XSU("Sucre", "SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE"),
    SBD("Solomon Islands Dollar", "SOLOMON ISLANDS"),
    SOS("Somali Shilling", "SOMALIA"),
    SSP("South Sudanese Pound", "SOUTH SUDAN"),
    LKR("Sri Lanka Rupee", "SRI LANKA"),
    SDG("Sudanese Pound", "SUDAN (THE)"),
    SRD("Surinam Dollar", "SURINAME"),
    SZL("Lilangeni", "SWAZILAND"),
    SEK("Swedish Krona", "SWEDEN"),
    CHE("WIR Euro", "SWITZERLAND"),
    CHF("Swiss Franc", "SWITZERLAND"),
    CHW("WIR Franc", "SWITZERLAND"),
    SYP("Syrian Pound", "SYRIAN ARAB REPUBLIC"),
    TWD("New Taiwan Dollar", "TAIWAN (PROVINCE OF CHINA)"),
    TJS("Somoni", "TAJIKISTAN"),
    TZS("Tanzanian Shilling", "TANZANIA,UNITED REPUBLIC OF"),
    THB("Baht", "THAILAND"),
    TOP("Pa’anga", "TONGA"),
    TTD("Trinidad and Tobago Dollar", "TRINIDAD AND TOBAGO"),
    TND("Tunisian Dinar", "TUNISIA"),
    TRY("Turkish Lira", "TURKEY"),
    TMT("Turkmenistan New Manat", "TURKMENISTAN"),
    UGX("Uganda Shilling", "UGANDA"),
    UAH("Hryvnia", "UKRAINE"),
    AED("UAE Dirham", "UNITED ARAB EMIRATES (THE)"),
    GBP("Pound Sterling", "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)"),
    USD("US Dollar", "UNITED STATES OF AMERICA (THE)"),
    USN("US Dollar (Next day)", "UNITED STATES OF AMERICA (THE)"),
    UYI("Uruguay Peso en Unidades Indexadas (URUIURUI)", "URUGUAY"),
    UYU("Peso Uruguayo", "URUGUAY"),
    UZS("Uzbekistan Sum", "UZBEKISTAN"),
    VUV("Vatu", "VANUATU"),
    VEF("Bolivar", "VENEZUELA (BOLIVARIAN REPUBLIC OF)"),
    VND("Dong", "VIET NAM"),
    YER("Yemeni Rial", "YEMEN"),
    ZMW("Zambian Kwacha", "ZAMBIA"),
    ZWL("Zimbabwe Dollar", "ZIMBABWE");


    private final String currencyName;
    private final String countryName;

    CountryCurrencyCodes(String currencyName, String countryName) {
        this.currencyName = currencyName;
        this.countryName = countryName;
    }

    public String getCurrencyName() {
        return currencyName;
    }

    public String getCountryName() {
        return countryName;
    }
}
